### ISSUE TITLE
Markers drift between cameras sub-groups

### ISSUE THREAD

**Issue by Shaked198** [diegoaldarondo/Label3D#14]
Thank you for this user-friendly tool :-)
We are using a setup of 5 cameras with a square arena, a single camera from the top, and 4 - one above each corner.
After calibration, the cameras' arrangement looks great, also when plotting it from the Label3D object. It seems that the positions and orientations are fine.
During labeling, we get matching points for each sub-group of cameras, one sub-group includes 2 adjacent cameras and the top one while the other sub-group the other two. Marking a point in one sub-group looks good within its cameras but really 'off' in the other group's cameras.

We have tried using different L-frames and checkerboards to solve the issue without success.

Additional info:
Win10
Matlab 2019b
CV toolbox version 9.1
Intrinsics error <1 pixel for all cameras
1640X1232 image resolution
arena size ~1 m^2

**Comment by diegoaldarondo** [comment]
This is my general protocol for camera calibration:

1. Calibrate each camera's intrinsics with the MATLAB camera calibrator app. Focus on covering the entire field of view of the camera, especially in the areas where the subject will be. This might involve removing any walls that limit the locations you can put the checkerboard during calibration (you can add them back in afterward). I recommend a minimum of 30 images per camera.
2. Extrinsic calibration with a checkerboard pattern. Place the checkerboard such that it can be detected by all cameras. Automatically detect the checkerboard points with Matlab or opencv's tools, and estimate each camera's world pose with matlab or opencv's tools. 
3. Qualitatively check the calibration with Label3D. You can do this by reprojecting 3d points into each image, or by clicking on features in the image and triangulating. 

This process might take a few tries to get things perfectly calibrated, but it's never failed me. If you still have trouble, I would try using an AprilTag board instead of checkerboards, as MATLAB CV toolbox says that they are more robust. I've never tried them yet, so I can't give my experience.

**Comment by spoonsso** [comment]
@Shaked198 , it sounds like your subgroups are not calibrated to each other? If so, then points from one subgroup will not reproject correctly into the other subgroup, as the orientations of one subgroup wouldn't be fit relative to the orientations in the other.

**Comment by Shaked198** [comment]
Thanks guys, I am doing a calibration protocol similar to what is suggested above. Just to be clear, we do all is listed below:
1) Intrinsics calc using a checkerboard for each camera, results with very low errors (I use more than 500 frames).
2) L-frame snapshots from **all** cameras, I also tried to use the checkerboard instead. reconstruction of cameras arrangement looks good with the L-frame and almost perfect with the checkerboard.
3) We have tried several times to use the refinement process (snapshots of L-frame and checkerboard together), it usually does not improve results so much as they look almost perfect before that.

After all that, the reconstructed cameras arrangement looks very good, both using CV toolbox and Label3D plots. However, when proceeding to labeling, marking points in cameras 1+2 triangulates well to cam3 but is 'off' in 4+5. Marking points in cameras 4+5 shows good match between them but triangulates bad to 1-3.
Camera 2 is the one from the top, 1,3,4,5 are located on the corners.

I would appreciate any suggestions,
Thank you

**Comment by diegoaldarondo** [comment]
If I had to guess, I would say the issue is probably with the extrinsic calibration. There are many things you can do, but it's hard to give a recommendation without knowing more about your problem and the setup. 

1. Please share the code you're using to estimate the world poses. (It sounds like you may be using the code in the dannce repo, but I just want to be sure)
2. Any images you have of the calibration process would also be helpful. Examples could include an intrinsic calibration image, an extrinsic checkerboard image with reprojected world points, an image of the camera poses, an image showing the problem with triangulation, etc. 

And I suspect you have tried this, but whenever I have problems with extrinsic calibration I can usually solve it by just repeating the extrinsic calibration process after moving the checkerboard to a slightly different place.

**Comment by Shaked198** [comment]
Thanks again,
For now we found some frame rate issue, hopefully solving it will make things better.
We managed to get good results for physical landmarks (not body parts) in the arena between cameras so I guess for now it is fine. I'll write an updated status when we get over current issues.
